nrfconnect/sdk-sidewalk

samples/sid_dut/src/sid_dut_shell.c, samples/template_subghz/src/board_events.c, utils/src/shell.c
@totyz I changed initial state to `SID_STATE_NOT_READY`, could you check does it have an impact to yours tests?
=> Fix coverity findings

.github/workflows/on_commit.yml, .github/workflows/verify_new_ncs.yml, scripts/ci/replace_nrf_revision_in_west.py
at 1:00 am every day build sidewalk samples and tests using the latest avaliable version of nrf
=> github: add nightly compatiblity check with nrf

LICENSE.txt
KRKNWK-16762
Signed-off-by: Robert Gałat <robert.galat@nordicsemi.no>
=> license: Update license for Amazon

.github/workflows/on_PR.yml, .github/workflows/on_commit.yml, .github/workflows/post_PR_comment.yml, scripts/ci/combine_twister_reports.py, scripts/ci/compare_size_reports.py, scripts/ci/replace_nrf_revision_in_west.py
Every PR will now have automatic comment that shows the memory usage difference caused by the change, and absolute value of the memory used.
=> github: add comment with change in memory usage

.github/workflows/on_PR.yml, .github/workflows/post_PR_comment.yml, scripts/ci/compare_size_reports.py
add option to print only elements that were different
=> github: simplify memory usage table

samples/sensor_monitoring/boards/nrf52840dk_nrf52840.overlay, samples/sid_dut/boards/nrf52840dk_nrf52840.overlay, samples/template_subghz/boards/nrf52840dk_nrf52840.overlay, samples/template_subghz/boards/nrf52840dk_nrf52840_release.overlay, subsys/config/common/src/app_subGHz_config.c, subsys/sal/sid_pal/include/sid_gpio_utils.h, subsys/sal/sid_pal/src/sid_gpio_utils.c, subsys/sal/sid_pal/src/sid_pal_serial_bus_spi.c, tests/functional/spi_bus/CMakeLists.txt, tests/functional/spi_bus/boards/nrf52840dk_nrf52840.overlay, tests/manual/power/boards/nrf52840dk_nrf52840.overlay, tests/manual/power/boards/nrf52840dk_nrf52840_release.overlay, tests/unit_tests/sid_pal_gpio_utils/src/main.c
KRKNWK-16768
Signed-off-by: Robert Gałat <robert.galat@nordicsemi.no>
=> Move semtech config to DTS

.github/workflows/on_PR.yml, .github/workflows/on_commit.yml, .github/workflows/post_PR_comment.yml
save build log
split building samples using matrix to distribute load even move generation of PR commit message to separate action unify action for PR and commit
=> github: save build log

.github/workflows/common_build_samples.yml
use this workflow for commit, PR, and schedule
=> github: prepare common workflow for building

.github/workflows/on_PR.yml, .github/workflows/post_PR_comment.yml
workflow_run.event does not hold to the PR number of calling workflow. 
The PR number had to be retreived with artifacts
=> github: pass PR number as artifact

.github/workflows/common_build_samples.yml, .github/workflows/verify_new_ncs.yml
In case of building for nrf main, the path to sidewalk has been invalid
=> github: fix incorrect path in common_build_samples

doc/setting_up_sidewalk_environment/setting_up_sidewalk_product.rst
Update python command to install mfg tools
=> doc: update windows setup commands

.github/workflows/common_build_samples.yml, scripts/generate_version_info.py
[KRKNWK-16859](https://projecttools.nordicsemi.no/jira/browse/KRKNWK-16859)
=> Fix memory report diff on pr

.github/workflows/tag_action.yml
attach buiild artifacts to relase
=> GitHub: add build artifacts to release

.github/workflows/on_commit.yml
=> GitHub: Enable manual trigger of on commit plan

README.rst, doc/additional_resources.rst
* README sidewalk link was obsolate
* Fix test specification link
=> doc: update amazon sidewalk documentation link

tests/manual/simple_bootloader/CMakeLists.txt, tests/manual/simple_bootloader/Kconfig, tests/manual/simple_bootloader/child_image/mcuboot/Kconfig.root, tests/manual/simple_bootloader/child_image/mcuboot/prj.conf, tests/manual/simple_bootloader/prj.conf, tests/manual/simple_bootloader/src/main.c
[KRKNWK-12220]
LED2 is on when application successfully starts
=> tests: Turn on led in simple bootloader app

.github/workflows/common-run-ut-on-dut.yml, .github/workflows/common_build_samples.yml, .github/workflows/on_PR.yml, .github/workflows/on_commit.yml, .github/workflows/post_PR_comment.yml, .github/workflows/verify_new_ncs.yml
run tests on DUT using self hosted runner
=> GitHub: Run on board Unit tests in Actions

.github/workflows/common-run-ut-on-dut.yml
=> GitHub: fix common-run-ut-on-dut.yml

.github/workflows/post-pr-comment.yml
=> github: Update post-pr-comment.yml

README.rst
=> doc: fix GitHub badge link

.github/workflows/post-pr-comment.yml
Base revision of the FLASH usage was not updated.
Pick the right action workflow to fetch the base flash usage
=> Github: fix PR comment

west.yml
=> NRF upmerge 2023_28_05

.github/workflows/nrf-upmerge-pr.yml
add Sidewalk Team email for automatic commits
=> Github: add committer and author to GH actions

west.yml
=> NRF upmerge 2023_30_05 (v2.4.0-rc2)

samples/sensor_monitoring/Kconfig, samples/sensor_monitoring/include/sm_timers.h, samples/sensor_monitoring/src/sm_callbacks.c, samples/sensor_monitoring/src/sm_notifications.c, samples/sensor_monitoring/src/sm_task.c, samples/sensor_monitoring/src/sm_timers.c
KRKNWK-16974
Signed-off-by: Robert Gałat <robert.galat@nordicsemi.no>
=> sensor: move timer configuration to Kconfig

tests/unit_tests/pal_temperature/CMakeLists.txt, tests/unit_tests/pal_temperature/Kconfig, tests/unit_tests/pal_temperature/src/dummy_sensor.c, tests/unit_tests/pal_temperature/src/dummy_sensor.h, tests/unit_tests/pal_temperature/src/kconfig_mock.h, tests/unit_tests/pal_temperature/src/main.c, tests/unit_tests/pal_temperature/testcase.yaml
KRKNWK-16007
Signed-off-by: Robert Gałat <robert.galat@nordicsemi.no>
=> tests: Add unit tests for temperature sensor

.github/workflows/on-pr.yml
=> GitHub: Publish tests results on PR action summary

west.yml
=> NRF upmerge 2023_01_06

.github/workflows/common-build.yml, .github/workflows/common-run-tests.yml, .github/workflows/on-commit.yml, .github/workflows/on-pr.yml, .github/workflows/post-pr-comment.yml, .github/workflows/verify-new-ncs.yml
enable new boards,
split building and testing
=> github: refactor actions

.github/workflows/common-build.yml
=> GH: fix combine test artifacts

.github/workflows/common-run-tests.yml
=> GH: fix platform on dut tests

.github/workflows/common-build.yml, .github/workflows/common-run-tests.yml
=> GH: separate ut with dut tests

.github/workflows/common-build.yml
=> GH: fix merging dut artifacts

.github/workflows/common-run-tests.yml
=> GH: fix exclude platform for twister dut tests

.github/workflows/common-run-tests.yml
=> GH: disable tests on DUT

.github/workflows/on-pr.yml, .github/workflows/post-pr-comment.yml, .github/workflows/tag-action.yml
=> GH: fix release action

.github/workflows/common-run-tests.yml
=> GH: twister arguments

doc/compatibility_matrix.rst, doc/index.rst
=> doc: added compatibility matrix

README.rst
=> doc: add support section to readme

west.yml
=> NRF upmerge 2023_11_06

west.yml
=> NRF upmerge 2023_18_06

west.yml
=> NRF upmerge 2023_02_07

doc/sidewalk_known_issues.rst, doc/sidewalk_release_notes.rst
=> doc: expermiental support for nrf53

west.yml
=> NRF upmerge 2023_16_07

doc/requirements-doc.txt, internal_west.yml, tests/unit_tests/pal_timer/src/main.c, tests/unit_tests/sid_pal_gpio_utils/src/main.c
=> NRF upmerge 2023_23_07

doc/index.rst
added a note with license disclaimer.
link to the license tbc.
=> doc: add license disclaimer

internal_west.yml
=> NRF upmerge 2023_23_08

internal_west.yml
=> NRF upmerge 2023_27_08

doc/sidewalk_known_issues.rst
* add KRKNWK-17374 (semaphore assert) to known issues
=> Sidewalk update

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2023_10_09

samples/sid_dut/CMakeLists.txt, samples/sid_dut/child_image/hci_rpmsg/Kconfig.root, samples/sid_dut/child_image/hci_rpmsg/prj.conf, samples/sid_dut/child_image/hci_rpmsg/prj_release.conf
=> samples: sid dut add hci configuration

.github/workflows/common-build.yml, .github/workflows/common_run_dut_ut.yml, .github/workflows/on-commit.yml, .github/workflows/on-pr.yml, .github/workflows/publish_test_results.yml, .github/workflows/verify-new-ncs.yml, scripts/ci/combine_twister_reports.py
replace unreliable raspberry pi with linux on x86 platform
=> GHA: add linux x86 self hosted test node for dut

internal_west.yml
=> NRF upmerge 2023_24_09

doc/setting_up_sidewalk_environment/requirements.rst
added units info to requirements table.
=> doc: added units information

subsys/sal/sid_pal/src/pal_init.c, subsys/sal/sid_pal/src/sid_pal_serial_bus_spi.c
Disable ble radio on application init
=> Fix high current cosumption in subGHz samples on nRF53

doc/setting_up_sidewalk_environment/setting_up_sidewalk_gateway.rst, doc/sidewalk_known_issues.rst
Updated to match the ncs layout.
=> doc: known issues update

subsys/sal/sid_pal/src/CMakeLists.txt, subsys/sal/sid_pal/src/sid_temperature_mock.c
[KRKNWK-17111]
[KRKNWK-17111]: https://nordicsemi.atlassian.net/browse/KRKNWK-17111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> pal: info for developers on mock temperature use

.github/docker/Dockerfile, .github/workflows/publish_docker_image.yml
create docker image to use in automations
=> GHA: create docker image for automations

.github/workflows/common-build.yml, .github/workflows/common_run_dut_ut.yml, .github/workflows/on-commit.yml, .github/workflows/on-pr.yml, .github/workflows/verify-new-ncs.yml
github actions overwrites the HOME variable,
this prevents nrfutil from finding the toolchain
=> GHA: fix toolchain-manager in HGA

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2023_08_10

doc/sidewalk_known_issues.rst
[KRKNWK-16843]
[KRKNWK-16843]: https://nordicsemi.atlassian.net/browse/KRKNWK-16843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: update known issues

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2023_15_10

samples/sid_dut/src/sid_thread.c, samples/template_ble/src/sidewalk_callbacks.c, samples/template_subghz/src/sidewalk_callbacks.c, utils/include/json_printer.h, utils/include/sidTypes2Json.h, utils/include/sidTypes2str.h, utils/src/shell.c
add types to json macros, use printing to array for sid_dut
=> JSON: improve JSON printer

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2023_22_10

doc/ncs_links.rst
fixed a link for the nrf53 getting started guide
=> doc: fixed link for nrf53

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2023_26_10

.github/workflows/common_run_dut_ut.yml
workaround to failing tester machine
=> GHA: dut tests continue on error

doc/conf.py, doc/requirements-doc.txt, doc/sidewalk_release_notes.rst
Added previous known issues per release.
Added toggle extension.
=> doc: included previous known issues

.github/workflows/nrf-upmerge-pr.yml, doc/ncs_links.rst, doc/ncs_links_update.sh, doc/setting_up_sidewalk_environment/setting_up_sdk.rst, internal_west.yml
=> NRF upmerge 2023_12_11

tests/functional/critical_region/CMakeLists.txt, tests/functional/critical_region/Kconfig, tests/functional/critical_region/prj.conf, tests/functional/critical_region/src/main.c, tests/functional/critical_region/testcase.yaml
[KRKNWK-18043]
[KRKNWK-18043]: https://nordicsemi.atlassian.net/browse/KRKNWK-18043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests: add critical region tests

doc/ncs_links.rst, doc/setting_up_sidewalk_environment/setting_up_sdk.rst
=> doc: fix for links and reordering

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2023_19_11

utils/include/sidewalk_version.h
to help report issues add board to initial log message
=> log: add board name to boot up log

doc/setting_up_sidewalk_environment/setting_up_sdk.rst, doc/setting_up_sidewalk_environment/setting_up_sidewalk_product.rst
updated few setup items as per jira KRKNWK18136.
=> doc: Doc improvements

utils/include/sidTypes2Json.h
remove invalid JSON_OBJ wrapper in JSON_VAL_sid_msg_desc
=> JSON: fix double {} on JSON_VAL_sid_msg_desc

internal_west.yml
=> NRF upmerge 2024_11_01

doc/conf.py
updated the year to 2024
corrected the project name
=> doc: homepage small fix

.github/workflows/DUT_tests.yml, .github/workflows/common-build_and_run.yml
split test on hw for every board to speed up tests
=> GHA: use separate runner for every board

internal_west.yml
=> NRF upmerge 2024_04_02

.github/workflows/publish-documentation.yml
added graphviz, plantuml and jre
=> doc: install requirements for doc in GHA

samples/template/src/cli/app_shell.c, samples/template/src/sensor_monitoring/app_buttons.c, samples/template/src/sensor_monitoring/app_rx.c
Fix static analysis issues reported by Coverity in CI
=> Fix coverity issues

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2024_22_02

Kconfig, subsys/config/common/src/app_subGHz_config.c
KRKNWK-18525
move the magic number to kconfig
=> build: make trim cap value a Kconfig

internal_west.yml
=> NRF upmerge 2024_25_02

doc/setting_up_sidewalk_environment/setting_up_sidewalk_product.rst, samples/sid_end_device/Kconfig, samples/sid_end_device/sample.yaml
Fix command to provision Sidewalk device
=> doc: fixes

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2024_03_03

doc/compatibility_matrix.rst
updated compatiblity matrix table
=> doc: small table update

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge v2.6.0

samples/sid_end_device/src/cli/app_dut.c, samples/sid_end_device/src/cli/app_shell.c, samples/sid_end_device/src/hello/app.c, samples/sid_end_device/src/sensor_monitoring/app.c, samples/sid_end_device/src/sensor_monitoring/app_tx.c, subsys/sal/sid_pal/src/sid_mfg_storage.c, utils/include/sidTypes2str.h, utils/src/settings_utils.c, utils/src/sid_on_dev_cert.c, utils/src/sid_on_dev_cert_cli.c
=> build: fix warning pointed out by static analysis

doc/ncs_links.rst, internal_west.yml
=> NRF upmerge 2024_17_03

internal_west.yml
=> NRF upmerge 2024_24_03

doc/compatibility_matrix.rst, doc/samples/samples_list.rst, doc/samples/sid_end_device.rst, doc/setting_up_sidewalk_environment/setting_up_sidewalk_product.rst
Small improvements for nrf54l15
=> doc: small ux improvements

doc/sidewalk_release_notes.rst
added link to cs release.
Section to be removed after the release.
(branch, hash, pull/XXX/head)
manifest-pr-skip (remove this line to create PR in NRF)
JIRA ticket:
=> doc: add cs note to release notes

doc/sidewalk_release_notes.rst
udpated the tag name
(branch, hash, pull/XXX/head)
manifest-pr-skip (remove this line to create PR in NRF)
JIRA ticket:
=> doc: fix tag name

.github/pull_request_template.md, .github/workflows/compare_config.yml, .github/workflows/on-commit.yml, .github/workflows/on-pr.yml, .github/workflows/on-pr_nrf_manifest_update_PR.yml, .github/workflows/on-pr_publish_comment.yml
```yaml
Jenkins:
```
JIRA ticket:
=> gha: add yaml configuration to PR template

.github/workflows/on-pr_nrf_manifest_update_PR.yml, .github/workflows/run_tests_dut.yml
nrf was not updated during the action
```yaml
Jenkins:
```
JIRA ticket:
=> gha: clean .west before running tests on self hosted runners

.github/workflows/on_dispatch_publish-documentation.yml, README.rst
use docs.nordicsemi.com for hosting release version of doc.
```yaml
Jenkins:
```
JIRA ticket:
=> doc: update link to release versions of documentation

README.rst
remove duplicated documentation links
```yaml
Jenkins:
```
JIRA ticket:
=> doc: Update readme

samples/sid_end_device/src/sidewalk.c, subsys/sal/sid_pal/src/sid_assert.c
```yaml
Jenkins:
```
JIRA ticket: KRKNWK-19077
=> Krknwk 19077 usage fault on stress

samples/sid_end_device/CMakeLists.txt, samples/sid_end_device/include/cli/app_dut.h, samples/sid_end_device/include/cli/app_shell.h, samples/sid_end_device/include/sidewalk.h, samples/sid_end_device/src/cli/app.c, samples/sid_end_device/src/cli/app_dut.c, samples/sid_end_device/src/cli/app_shell.c, samples/sid_end_device/src/hello/app.c, samples/sid_end_device/src/sbdt/file_transfer.c, samples/sid_end_device/src/sensor_monitoring/app.c, samples/sid_end_device/src/sensor_monitoring/app_tx.c, samples/sid_end_device/src/sidewalk.c, samples/sid_end_device/src/sidewalk_events.c, subsys/hal/src/memory.c, tests/unit_tests/sid_dut_shell/mock/sidewalk_mock.h
move events to functions
for now only dut is compiling
TODO:
```yaml
Jenkins:
```
JIRA ticket:
=> sample: refactor events for application

doc/links.rst
fixed in the 2.7.0 doc release as well.
```yaml
Jenkins:
```
JIRA ticket:
=> doc: small link fix

.github/docker/Dockerfile, subsys/sal/sid_pal/src/sid_ble_connection.c, tests/unit_tests/pal_ble_adapter/src/main.c, tests/unit_tests/sid_ble_connection/src/main.c
```yaml
Jenkins:
```
JIRA ticket: 
The api for function bt_conn_cb_register has been changed this commit applies the change
=> ble: fix api for bt_conn_cb_register

samples/sid_end_device/src/sidewalk.c, samples/sid_end_device/src/sidewalk_events.c
```yaml
Jenkins:
```
JIRA ticket: KRKNWK-19262
by statically initializing the queue we prevent issues with events.
=> sample: fix sidewalk_thread msgq

samples/sid_end_device/src/cli/app_dut.c, samples/sid_end_device/src/sidewalk_events.c
```yaml
Jenkins:
```
JIRA ticket: 
add warning to DUT
=> app: add check for mfg at platform_init

doc/setting_up_sidewalk_environment/setting_up_hardware.rst
```yaml
Jenkins:
```
PR removes the additional "0" for pins mapping.
=> doc: pin alignment

tests/functional/crypto/src/main.c
[KRKNWK-19270]
Fixed in https://github.com/nrfconnect/sdk-sidewalk/commit/967d6dc31b81c35c1ae5ef9663d44cc8ba74bbd5
```yaml
Jenkins:
```
JIRA ticket: 
[KRKNWK-19270]: https://nordicsemi.atlassian.net/browse/KRKNWK-19270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests: remove outdated todo comment

.gitignore
In case when files are generated in the tools folder then should be ignored.
```yaml
Jenkins:
```
=> git: Ignore manufacturing hex and binary files.

scripts/ci/run_ut.sh
Retry unit test when failed.
```yaml
Jenkins:
```
JIRA ticket:
=> scripts: Update run UT on HW

samples/sid_end_device/include/cli/app_shell.h, samples/sid_end_device/src/cli/app_shell.c
add command to dut shell to enter into DFU
```yaml
Jenkins:
```
JIRA ticket:
=> dut: add DFU service to dut sample

subsys/sal/sid_pal/src/sid_mfg_storage.c
[KRKNWK-19280]
```yaml
Jenkins:
```
JIRA ticket: 
[KRKNWK-19280]: https://nordicsemi.atlassian.net/browse/KRKNWK-19280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> pal: protect sidewalk mfg data flash partition

doc/additional_resources.rst
[KRKNWK-19269]
Links presents how to use approtect
```yaml
Jenkins:
```
JIRA ticket: 
[KRKNWK-19269]: https://nordicsemi.atlassian.net/browse/KRKNWK-19269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: add nrf52 nrf53 production programming guides

doc/links.rst, doc/releases_and_migration/migration_guide_v280.rst, doc/samples/sid_end_device.rst
Minor fixes after review
```yaml
Jenkins:
```
JIRA ticket:
=> doc: precise trusted storage description

subsys/sal/sid_pal/src/sid_pal_serial_bus_nrfx_spi.c
Set SPI bus frequency in init function.
```yaml
Jenkins:
```
JIRA ticket:
=> pal: spi: Move SPI bus speed setting to init function.

samples/sid_end_device/boards/nrf52840dk_nrf52840.overlay, subsys/config/common/src/app_subGHz_config.c
[KRKNWK-19537]
```yaml
Jenkins:
```
JIRA ticket: 
[KRKNWK-19537]: https://nordicsemi.atlassian.net/browse/KRKNWK-19537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> samples: fix cs pin config for nrf52

subsys/config/common/src/app_subGHz_config.c
select the correct gpio for CS to pass to Sidewalk config
```yaml
Jenkins:
```
JIRA ticket:
=> GPIO: fix client_selector for subGHz config

Kconfig, Kconfig.dependencies, samples/sid_end_device/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/sid_end_device/boards/nrf54l15dk_nrf54l15_cpuapp_ns.overlay, samples/sid_end_device/pm_static_nrf54l15dk_nrf54l15_cpuapp_ns.yml, samples/sid_end_device/sample.yaml, samples/sid_end_device/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/sid_end_device/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp_ns.overlay, subsys/sal/sid_pal/src/sid_mfg_storage.c
[KRKNWK-19489]
Experimental support (build only) for
nrf54l15dk/nrf54l15/cpuapp/ns
```yaml
Jenkins:
```
JIRA ticket: 
[KRKNWK-19489]: https://nordicsemi.atlassian.net/browse/KRKNWK-19489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> samples: add nrf54l15dk with tf-m

Kconfig, samples/sid_end_device/sample.yaml, utils/include/sidewalk_version.h
KRKNWK-19484
remove version, as it is already printed in logs, and replace it with application name that can be configured with KConfig.
```yaml
Jenkins:
test-sdk-sidewalk: handling-APP_NAME
```
JIRA ticket:
=> log: replace duplicated version with the configurable name

doc/compatibility_matrix.rst
removed pdk
```yaml
Jenkins:
```
JIRA ticket:
=> doc: cm table small fix

samples/sid_end_device/sample.yaml
for testing purposes
```yaml
Jenkins:
test-sdk-sidewalk: bleOnlySidDut
```
JIRA ticket:
=> samples: add dut ble only

doc/compatibility_matrix.rst, doc/includes/memory_requirement.txt, doc/links.rst, doc/releases_and_migration.rst, doc/releases_and_migration/release_notes_v290.rst, doc/samples/samples_list.rst, doc/setting_up_sidewalk_environment/setting_up_sidewalk_prototype.rst
Made few fixes for better readability.
Updated links and added release notes placeholder. Removed note about sample model change from 2.6.0
```yaml
Jenkins:
```
JIRA ticket:
=> doc: 2.9.0 pre-release adjustments

doc/compatibility_matrix.rst
small update
```yaml
Jenkins:
```
JIRA ticket:
=> doc: compatibilty matrix

Kconfig.dependencies
This reverts commit 5b5cc727b18b7249985043b9c1975799869c7f10.
```yaml
Jenkins:
```
JIRA ticket:
=> build: remove experimental label for nrf54l10

doc/compatibility_matrix.rst, doc/links.rst
changed 2.8 status
```yaml
Jenkins:
```
JIRA ticket:
=> doc: small compatibility matrix fix

samples/sid_end_device/Kconfig.defconfig
Reverts nrfconnect/sdk-sidewalk#664
Change in NRF is still not ready
=> Revert "ble: Remove CONFIG_BT_BUF_ACL_RX_COUNT"

samples/sid_end_device/Kconfig.defconfig
This reverts commit 7767d43fb45be20347704238bfaf1dbd7abe8bed.
```yaml
Jenkins:
```
JIRA ticket:
=> Revert "Revert "ble: Remove CONFIG_BT_BUF_ACL_RX_COUNT""

.github/docker/Dockerfile, .github/workflows/on_docker_change.yml
fix filter of triggering on tags, add tags to docker containers
```yaml
Jenkins:
```
JIRA ticket:
=> GHA: fix docker container tags

.github/pull_request_template.md
Introduce new CI parameter - Filters
```yaml
Jenkins:
```
JIRA ticket:
=> GHA: Change PR template

.github/workflows/on-push-tag.yml, .github/workflows/samples_build.yml
push documentation when creating release
```yaml
Jenkins:
```
JIRA ticket:
=> GHA: publish documentation on relase

.github/workflows/on-push-tag.yml, .github/workflows/on_push_publish-documentation.yml
fix release documentation build name
```yaml
Jenkins:
```
JIRA ticket:
=> doc: temporary disable documentation push

.github/workflows/compare_config.yml, .github/workflows/nrf-upmerge-pr.yml, .github/workflows/on-pr_publish_comment.yml, .github/workflows/on_push_publish-documentation.yml
```yaml
Jenkins:
```
JIRA ticket: [KRKNWK-20066](https://nordicsemi.atlassian.net/browse/KRKNWK-20066)
[KRKNWK-20066]: https://nordicsemi.atlassian.net/browse/KRKNWK-20066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Krknwk 20066 automatically update nrf

.github/workflows/nrf-upmerge-pr.yml
use script from sidewalk to update nrf in manifest
```yaml
Jenkins:
```
JIRA ticket:
=> GHA: add script to update nrf

.github/workflows/publish_documentation.yml, doc/custom.properties, doc/index.rst, doc/tags.yml
Switch to 'add-on' in naming of the publication.
=> doc: change zoomin properties and tags

doc/custom.properties, doc/tags.yml
fix name so it is consistenet with zoomin setup
```yaml
Jenkins:
```
JIRA ticket:
=> doc: fix package name

Kconfig.dependencies
to increase security generate new address for every advertising session
```yaml
Jenkins:
Filters:
- filter1:
test_name: TestCert*
- filter2:
tags: multilink
- filter3:
tags: messaging
- filter4:
tags: connection
```
JIRA ticket:
=> BLE: rotate BLE address with every advert

doc/known_issues.rst
adds the known issue after merging the ncs PR
```yaml
Jenkins:
```
=> doc: add KRKNWK20330 known issue
