nrfconnect/sdk-sidewalk

tests/validation/timer/src/main.c
The timer_arg_data is copy too late and incorrect data is handled by callback function.
=> Fix for fatal error in validation test

tests/manual/power/src/main.c
KRKNWK-16772
During refactoring part of the test has been accidentally deleted
=> tests: Add missing code to send messages in test

.github/workflows/post_PR_comment.yml
Additionally use default token for posting comments The author of the comment will be github-actions[bot] now, not NordicBuilder
=> github: fix workflow warning

README.rst
Badge has been added that show if all samples and tests build correctly on the latest commit on main branch
=> github: add badge with build status for main

doc/setting_up_sidewalk_environment/setting_up_sdk.rst
Setup gives error if the verify west path command " west manifest --path" is preformed after updating west manifest path and before doing a west update. 
Propose doing west update before verifying manifest path
=> Do west manifest --path after west update

.github/workflows/nrf_upmergePR.yml, scripts/ci/replace_nrf_revision_in_west.py
KRKNWK-14753
On every Sunday at 01:00 create PR with the changed version of NRF to the most up to date revision.
The PR will trigger standard PR actions, so build check by github, and tests on Jenkins
=> github: create weekly PR with NRF upmerge

.github/workflows/common_build_samples.yml
Building step 2/3 of tests takes almost twice the time of other steps. It is therefore the bottle neck, by spliting this job to more tasks, it will distribute the load more evently and reduce the build time
=> GitHub: increase paralel matrix for slowest job

scripts/ci/fill_hardware_map.py
recover boards for both modes AUTO and user_devconf passed as parameter to run_ut.sh 
remove additional debug port for the newest nrf52 boards 
do not use nrf52840 <2.0.0
use logging module
Signed-off-by: Tomasz Tyzenhauz <tomasz.tyzenhauz@nordicsemi.no>
=> Scripts: fix generation of hardware map for twister UT

utils/src/nordic_dfu.c
this log creates too much messages that do not carry any benefit
=> log: remove log with upload progress

tests/manual/ble/sample.yaml, tests/manual/log/sample.yaml
two manual tests did not have build_only flag,
and automated test framework failed on attempt to run those tests (Those tests do not use any standard framework, and require human to assess the output and verify if it is correct)
=> tests: add build_only flag for manual tests on DUT

doc/testing_samples/sidewalk_testing.rst, tests/unit_tests/pal_critical_region/testcase.yaml, utils/src/nordic_dfu.c
KRKNWK-16267
added 2 patterns, to signal Entering into DFU state, and to show transfer in progress
=> DFU: implemented LED signal for DFU state

.devcontainer/devcontainer.json
lldb enalbes debugging for native posix.
If clangd is used, plugin C/C++ which usualy provides debugger for native application is disabled. LLDB is used instead in that case.
Doxygen helps with commenting functions and file headers.
=> vscode: add lldb and doxygen to devenvironment

.github/workflows/common-run-tests.yml
exclude native posix, and unit testing, as it is tested in other node
=> GH: run only hw tests on self hosted node

scripts/ci/run_ut.sh
Add new parameter -p which can be used to narrow twister to work only with selected platforms. It can be passed multiple times.
=> scripts: Extend run_ut script by selecting platform to use

scripts/generate_version_info_overlay.py
Replaces the old NCS-specific Kconfig CONFIG_MCUBOOT_IMAGE_VERSION with the upstream zephyr CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION one when signing an image for MCUboot.
=> samples/applications: Replace Kconfig

Kconfig.dependencies
fixing build configuration for NRF PR
https://github.com/nrfconnect/sdk-nrf/pull/12112
=> Build: remove deprecated Kconfig option

Kconfig.dependencies, subsys/sal/sid_pal/src/sid_ble_connection.c, tests/unit_tests/pal_ble_adapter/src/main.c, tests/unit_tests/sid_ble_connection/src/main.c
[KRKNWK-17600]
Disable client features, including att mtu requests. Now the MTU request are made by gateway, nRF responds. It is observed the connection with gateway works better this way.
[KRKNWK-17600]: https://nordicsemi.atlassian.net/browse/KRKNWK-17600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> pal: Remove MTU request from nRF to gateway

samples/sensor_monitoring/boards/thingy53_nrf5340_cpuapp.conf, samples/sensor_monitoring/boards/thingy53_nrf5340_cpuapp.overlay, samples/sensor_monitoring/include/sm_buttons.h, samples/sensor_monitoring/sample.yaml, samples/sensor_monitoring/src/sm_buttons.c, samples/sensor_monitoring/src/sm_leds.c, samples/sensor_monitoring/src/sm_notifications.c
[KRKNWK-17773]
Add Thingy with Bosh temperature sensor
Co-authored-by:Krzysztof Taborowski <krzysztof.taborowski@nordicsemi.no>
[KRKNWK-17773]: https://nordicsemi.atlassian.net/browse/KRKNWK-17773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Sample: Add Thingy53 for Sensor monitor

.github/workflows/common-build.yml, .github/workflows/common_run_dut_ut.yml
In Build step after the actual build preformed by twister, there were commands that will always return status 0, therefore this step always returns pass
=> GHA: fix issue with reporting fail build as pass

subsys/ace/osal/osal_alloc.c
Fix a build error when this flag is enabled: the structure name changed in Zephyr 3.2:
```log
..ace/osal/osal_alloc.c:22:39: error: storage size of 'stat' isn't known
22 |         struct sys_heap_runtime_stats stat;
|                                       ^~~~
```
=> ace: error on CONFIG_SYS_HEAP_RUNTIME_STATS=y

samples/sensor_monitoring/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/sid_dut/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/sid_dut/boards/nrf5340dk_nrf5340_cpuapp_ns.overlay, samples/template_ble/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/template_subghz/boards/nrf5340dk_nrf5340_cpuapp.overlay
Set IPC thread priority to the highest value
to not collide with other threads.
Workaround for nRF53 know issue
when BLE and Flash operations are performed at the same time
Copied form https://github.com/nrfconnect/sdk-nrf/blob/3003f42ee1a14ac6ca6f3cb6990ea2fcc05bb6a7/samples/matter/template/boards/nrf5340dk_nrf5340_cpuapp.overlay#L15
=> samples: increase ipc thread priority

utils/include/application_states.h
The pervious one was in conflict with qpio forwarded to netcore
=> utils: change gpio notifier pins for nRF53

tests/manual/power/src/main.c, tests/manual/power_ble_only/src/main.c
In power tests external flash will be suspend only on nRF53. This allows to perform usb dfu on nRF52 in Sidewalk mode
=> tests: nRF52  wont suspend flash to save power

internal_west.yml
[KRKNWK-17935]
See bootloder current fix https://github.com/nrfconnect/sdk-nrf/pull/12825
[KRKNWK-17935]: https://nordicsemi.atlassian.net/browse/KRKNWK-17935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> manifest: update nrf revision with current fix

doc/setting_up_sidewalk_environment/requirements.rst
The adapter is not needed since Sidewalk Gateways has FFN feature.
=> doc: remove ble adapter requirement

doc/setting_up_sidewalk_environment/setting_up_sdk.rst
This step is not longer necessary since NCS v2.5.0 release.
=> doc: Don't checkout to sdk-nrf main

samples/template_subghz/CMakeLists.txt
Changed the path in the mcuboot CMakeLists.txt to
ensure that changes made in a cloned example persist
correctly.
Signed-off-by: Kelly Helmut Lord <helmut@helmutlord.com>
=> template_subghz: mcuboot Kconfig.root path changed

utils/src/shell.c
check if payload_size is smaller than out_limit.
This buffer overflow vuln is triggerable from user input by passing a long payload.
=> shell: fix buffer overwriting

subsys/sal/sid_pal/src/sid_pal_serial_bus_spi.c
Remove misleading warning with function name
=> pal: remove misleading log

utils/src/CMakeLists.txt
include path was pointing onto specific sample,
which caused issue with building on any other sidewalk sample. Remove faulty include
=> build: fix include path for cli configuration

Kconfig, samples/sid_end_device/Kconfig.defconfig, samples/sid_end_device/include/file_transfer.h, samples/sid_end_device/src/cli/app.c, samples/sid_end_device/src/cli/app_shell.c, samples/sid_end_device/src/file_transfer.c, samples/sid_end_device/src/hello/app.c, samples/sid_end_device/src/sensor_monitoring/app.c, samples/sid_end_device/src/sensor_monitoring/app_tx.c, samples/sid_end_device/src/sidewalk.c, subsys/hal/src/memory.c, tests/unit_tests/sid_dut_shell/src/main.c, utils/include/sidTypes2str.h
The packet descriptior should be coppied when moved from the callback. unlike the data argument we can not be sure
if it is valid outside the callback context.
=> file_transfer: copy packet descriptor for event

utils/src/sid_on_dev_cert_cli.c
it is safe to use strcpy, as bufer is allocated correctly use sid_hal_malloc for allocation
=> fix: compilaiton warning about strncpy

utils/src/nordic_dfu.c
Fix for ASSERTION FAIL [!arch_is_in_isr()]
zephyr/kernel/sched.c:1581
=> utils: remove sleep from dfu timer callback

.github/pull_request_template.md, .github/workflows/on-pr_nrf_manifest_update_PR.yml
if configured, creation of PR in Sidewalk will trigger new PR in NRF. PR in NRF will keep track the state of the PR in Sidewalk.
Remember to delete the PR in NRF if the PR gets closed without merging.
Create_NRF_PR=true
JIRA ticket: KRKNWK-18740
Detail description of the change
=> CI: automatically create PR in NRF

subsys/sal/sid_pal/src/sid_timer.c
Possible fix for sporadic test failures.
```
START - test_sid_pal_timer_arm
Assertion failed at ../../../../../../tests/functional/time/src/main.c:93: time_test_sid_pal_timer_arm: sid_pal_timer_is_armed(&test_timer) is false
```
Casting away a const qualifier can lead to undefined behavior. We are not modifying timer object anyway, co we can use const pointer further.
=> pal: remove unncessary timer casting

samples/sid_end_device/CMakeLists.txt, samples/sid_end_device/src/cli/app_shell.c, samples/sid_end_device/src/sensor_monitoring/app.c, utils/src/settings_utils.c
decrease level of some log message - might be misleading
(branch, hash, pull/XXX/head)
(true, false)
Create_NRF_PR=true
JIRA ticket: 
Detail description of the change
=> Logs quick fix

.github/pull_request_template.md, .github/workflows/on-pr.yml, .github/workflows/on-pr_nrf_manifest_update_PR.yml, .github/workflows/run_tests.yml, .github/workflows/samples_build.yml
fix size report generation,
fetch PR body from CLI (allow change and rerun tests) merge jobs for creating PR in nrf
(branch, hash, pull/XXX/head)
manifest-pr-skip (remove this line to create PR in NRF)
JIRA ticket: 
Detail description of the change
=> ci: improve GHA

scripts/ci/run_ut.sh
Twister starts use gcov tool by default.
Switch back to lcov
```yaml
Jenkins:
```
JIRA ticket:
=> scripts: Add lcov as coverage tool in run_ut script

samples/sid_end_device/include/sidewalk.h, samples/sid_end_device/src/cli/app.c, samples/sid_end_device/src/hello/app.c, samples/sid_end_device/src/sensor_monitoring/app.c, samples/sid_end_device/src/sidewalk.c
The issue has been investigated, and it was caused by the `sid_put_msg` performing shallow copy of the data to send. This was not intended, and will be fixed in next release.
Temporary fix for this issue, is to track the payload passed to `sid_put_msg` and free it when message has been send, or when there will be no further attempts with sending.
So this commit is temporary and should be reverted for the next release.
```yaml
Jenkins:
```
JIRA ticket: 
KRKNWK-18805
KRKNWK-19016
=> sample: fix issue with sending malformed payload on autoconnect

utils/src/nordic_dfu.c
```yaml
Jenkins:
```
JIRA ticket: 
https://github.com/zephyrproject-rtos/zephyr/pull/71700/files#diff-654399b6eb61835065817cf21e12ceaf86bb0a3d5582a2b85615c079a701dac0R26-R36
file `samples/subsys/mgmt/mcumgr/smp_svr/src/bluetooth.c` is the same functionality, and has the same change.
This additional parameter sd was missed during the upmerge integration
The change has been tested manually, and after entering into DFU mode, the device with proper address starts to advertise as expected. 
Waiting for merge for completion of the Jenkins.
=> DFU: transmit device name in scan response packet

samples/sid_end_device/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/sid_end_device/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_0_2_1.overlay, samples/sid_end_device/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.overlay
with the latest upmerge the additional entry in DTS was required. The change has not been propagated to bootloader configuration. This commit fixes the issue where the application did not swap after DFU.
```yaml
Jenkins:
```
JIRA ticket:
=> mcuboot: add DTS configuration for nrf54 bootloader

samples/sid_end_device/include/sidewalk.h, samples/sid_end_device/src/cli/app.c, samples/sid_end_device/src/cli/app_shell.c, samples/sid_end_device/src/hello/app.c, samples/sid_end_device/src/sbdt/file_transfer.c, samples/sid_end_device/src/sensor_monitoring/app.c, samples/sid_end_device/src/sensor_monitoring/app_tx.c, samples/sid_end_device/src/sidewalk.c, tests/unit_tests/sid_dut_shell/mock/sidewalk_mock.h
Some events have context allocated on heap,
but it was not freed in all states.
```yaml
Jenkins:
```
JIRA ticket:
=> sample: fix issue with memory leak on events

samples/sid_end_device/src/sensor_monitoring/app.c
```yaml
Jenkins:
test-sdk-sidewalk: test-branch
```
The tests show that sidewalk state change callback can be called before the tx task is fully initialized, and some events are dropped. Move the initialization of the app_tx thread before the sidewalk starts.
=> sensor_monitor: move app_start_tasks

samples/sid_end_device/src/cli/app_dut.c, samples/sid_end_device/src/hello/app.c, samples/sid_end_device/src/sbdt/dfu_file_transfer.c, samples/sid_end_device/src/sensor_monitoring/app.c, samples/sid_end_device/src/sensor_monitoring/app_tx.c, samples/sid_end_device/src/sidewalk_events.c, subsys/sal/sid_pal/src/pal_init.c
It may be confusing if an error value is erno or sid_error_t. All logs with sid_error_t have their string representation in logs now.
```yaml
Jenkins:
```
JIRA ticket:
=> log: add name to sid_error_t when printing.

subsys/sal/sid_pal/src/sid_crypto_keys.c, subsys/sal/sid_pal/src/sid_storage.c, tests/functional/crypto_keys/src/main.c
[KRKNWK-19459]
Check it a persistent key with a given key id
Is present in secure key storage
before setting a key buffer.
```yaml
Jenkins:
```
JIRA ticket: 
[KRKNWK-19459]: https://nordicsemi.atlassian.net/browse/KRKNWK-19459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> pal: verify if key id is in secure storage

samples/sid_end_device/prj.conf, samples/sid_end_device/prj_release.conf, tests/manual/simple_bootloader/pm_static_nrf52840dk_nrf52840.yml, tests/manual/simple_bootloader/pm_static_nrf54l15dk_nrf54l15_cpuapp.yml, tests/manual/simple_bootloader/pm_static_thingy53_nrf5340_cpuapp.yml, tests/unit_tests/pal_crypto/src/main.c, tests/unit_tests/sid_dut_shell/mock/shell_mock.h, tests/unit_tests/state_notifier/src/main.c, utils/include/state_notifier/state_notifier.h
The sidewalk sample linking places stack_protector from the C library in the init_array sections.
For proper initialization in Zephyr then content in this init_array section requires STATIC_INIT_GNU to be configured.
```yaml
NRF_revision: pull/16860/head
Jenkins:
```
JIRA ticket:
=> sample: set STATIC_INIT_GNU for the sidewalk sample

utils/sidewalk_dfu/Kconfig
Aligned the MCUmgr Bluetooth transport Kconfig with the latest changes from Zephyr.
Ref: [NCSDK-29061]
```yaml
NRF_revision: pull/17436/head
Jenkins:
```
JIRA ticket: 
[NCSDK-29061]: https://nordicsemi.atlassian.net/browse/NCSDK-29061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> utils: sidewalk_dfu: align the MCUmgr Bluetooth transport Kconfig

subsys/sal/sid_pal/src/sid_ble_connection.c, tests/unit_tests/sid_ble_connection/src/main.c
KRKNWK-19512
Just clean up, the sidewalk handlers filters events by the connection, but still in case of DFU, the old connection handler can be called.
```yaml
Jenkins:
```
JIRA ticket:
=> BLE: clean up registered connection callback

subsys/sal/sid_pal/src/sid_ble_connection.c, tests/unit_tests/sid_ble_connection/src/main.c
This reverts commit ba1964f38cde2e660fcb315b1cf8df66123d257d.
When we unregister disconnection callbacks too early (`sid_ble_conn_deinit`) ble can't be disconnected succesfully.
```
<inf> sid_ble_conn: BT Disconnected Reason: 0x0 = SUCCESS
<inf> sid_cli: sid_deinit returned 0 (SID_ERROR_NONE)
```
```yaml
Jenkins:
```
JIRA ticket:
=> Revert "BLE: clean up registered connection callback"

Kconfig, Kconfig.dependencies, subsys/sal/sid_pal/src/sid_ble_adapter.c, subsys/sal/sid_pal/src/sid_ble_advert.c
[KRKNWK-19515]
```yaml
Jenkins:
```
JIRA ticket: 
[KRKNWK-19515]: https://nordicsemi.atlassian.net/browse/KRKNWK-19515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> config: remove experimental label for SOC_NRF54L15

Kconfig, samples/sid_end_device/Kconfig, samples/sid_end_device/src/sidewalk.c
[KRKNWK-19515]
```yaml
NRF_revision: v2.8-branch
Jenkins:
```
JIRA ticket: 
[KRKNWK-19515]: https://nordicsemi.atlassian.net/browse/KRKNWK-19515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> samples: enable timeout for sidewalk msg put

tests/unit_tests/pal_assert/CMakeLists.txt, tests/unit_tests/pal_assert/Kconfig, tests/unit_tests/pal_assert/prj.conf, tests/unit_tests/pal_assert/src/main.c, tests/unit_tests/pal_assert/testcase.yaml
Assert tests to use zephyr unit testing framework. It fixes false negative result when the posix board was used.
```yaml
Jenkins:
```
JIRA ticket:
=> tests: port assert test to zephyr unit tests

lib/cortex-m33/lora_fsk/CMakeLists.txt, lib/cortex-m4/lora_fsk/CMakeLists.txt
This commit removes the manual lookup and linking of libgcc.a.
Linking of C and runtime libraries are the responsibility of the higher level build system which handles the toolchain and building of the executable.
Current sidewalk implementation is broken in the sense that it fails to consider the CPU architecture and just looks up any libgcc.a file.
For example the code might discover `arm-zephyr-eabi/12.2.0/libgcc.a` when instead `arm-zephyr-eabi/12.2.0/thumb/v8-m.main+fp/hard/libgcc.a` should be used, and thus causiong link errors such as:
```
error: /.../12.2.0/libgcc.a(_arm_muldf3.o):
conflicting CPU architectures 17/2
```
and:
```
error: zephyr/zephyr_pre0.elf uses VFP register arguments,
/.../12.2.0/libgcc.a(_fixunsdfdi.o) does not
```
=> cmake: removing manual linking of libgcc.a

tests_new/integration/assert/CMakeLists.txt, tests_new/integration/assert/Kconfig, tests_new/integration/assert/prj.conf, tests_new/integration/assert/src/main.c, tests_new/integration/assert/testcase.yaml
add test for assert
```yaml
Jenkins:
```
JIRA ticket:
=> tests: add integration test for assert

samples/sid_end_device/Kconfig.defconfig
CONFIG_BT_BUF_ACL_RX_COUNT has been deprecated in
https://github.com/zephyrproject-rtos/zephyr/pull/81747 CONFIG_BT_BUF_ACL_RX_COUNT_EXTRA has been introduced to replace it.
```yaml
NRF_revision: pull/19412/head
Jenkins:
```
JIRA ticket:
=> ble: Remove CONFIG_BT_BUF_ACL_RX_COUNT

.github/workflows/on_docker_change.yml, samples/sid_end_device/sample.yaml
Space-based list support has been removed from upstream Zephyr.
```yaml
#NRF_revision: pull/19726/head
Jenkins:
```
JIRA ticket:
=> samples: use native YAML lists

samples/sid_end_device/Kconfig
Logs are sent only to backends that are ready,
If some backend like SHELL takes some time to start, and other backend is already initialized.
The messages will not be sent to the uninitialled backend. The solution is to disable the unused backend
and therefore the logs will wait for the shell to initialize
```yaml
Jenkins:
```
JIRA ticket: KRKNWK-20023
=> log: disable RTT backend when SHELL is in use.

Kconfig, doc/includes/include_kconfig_common.txt, samples/sid_end_device/include/sidewalk.h
- Set CONFIG_SIDEWALK_LINK_MASK_LORA to LINK_TYPE_3
- Removed deprecated labels from physical link type prompts in Kconfig.
- Updated documentation to reflect the new configuration options for link types.
```yaml
Jenkins:
```
JIRA ticket:
=> samples: Set only lora on CONFIG_SIDEWALK_LINK_MASK_LORA

subsys/sal/sid_pal/src/CMakeLists.txt
Add missing CONFIG_ prefix to CONFIG_DEPRECATED_SIDEWALK_PAL_INIT Kconfig to *actually* allow the use of the deprecated pal_init.c file.
=> pal: fix misspelled Kconfig in CMakeLists.txt

doc/conf.py, doc/includes/include_building_and_running.txt, doc/index.rst, doc/links.rst, doc/releases_and_migration.rst, doc/releases_and_migration/migration_guide_addon_v010.rst, doc/requirements-doc.txt, doc/setting_up_sidewalk_environment/setting_up_sdk.rst
Review of the PR687
Added an extension for easy copy-pasting of code blocks.
```yaml
Jenkins:
```
JIRA ticket:
=> doc: new sidewalk setup doc review

.github/workflows/nrf-upmerge-pr.yml
some scripts can trigger only on main,
so smoe errors needed tobe fixed once merged.
```yaml
Jenkins:
```
JIRA ticket:
=> GHA: fix issue with GHA scripts

tests/manual/simple_bootloader/Kconfig.sysbuild
Set BOOT_SIGNATURE_TYPE_RSA in test application
```yaml
Jenkins:
Filters:
- filter1:
tags: dfu and smoke
```
JIRA ticket:
=> samples: Set BOOT_SIGNATURE_TYPE_RSA in simple_bootloader

Kconfig
Fixes issue where the incorrect SPI IDX would be set when trying to use another bus
```yaml
Jenkins:
```
JIRA ticket:
=> config: Fix order of default SPI IDX assignment

subsys/sal/sid_pal/include/bt_app_callbacks.h, utils/include/settings_utils.h
adds `extern "C"` guards to bt_app_callbacks header for cpp support
```yaml
Jenkins:
```
JIRA ticket:
=> sal: sid_pal: add support for cpp linker
